version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 7.0.102

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet build 

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish --configuration Release --output ./publish ./ '**/*.csproj'

artifacts:
  files:
    - ./**/*