version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0.1

  pre_build:
    commands:
      - echo Restore started on `date`

  build:
    commands:
      - echo Build started on `date`
      - dotnet build Answer.King.Api/Answer.King.Api.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./ Answer.King.Api/Answer.King.Api.csproj

artifacts:
  files:
    - ./**/*